
PolyDoc.processFiles{
    sourceFiles=[
        "../polyml/basis/ASN1.sml", "../polyml/basis/Signal.sml", "../polyml/basis/SingleAssignment.sml",
        "../polyml/basis/Thread.sml", "../polyml/basis/Universal.ML", "../polyml/basis/UniversalArray.ML",
        "../polyml/basis/Weak.sml"], template=NONE, outputFileOrDir="outputs", parent=NONE};


PolyDoc.processFiles{
    sourceFiles=[
        "../polyml/basis"], template=NONE, outputFileOrDir="outputs", parent=NONE};
